### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by no2cturne** [cloudscape-design/jest-preset#30]
### Package version

2.0.22

### Jest version

29.5.0

### node-versions

18.13.0

### npm-versions

9.8.1

### Description

When using `@cloudscape-design/jest-preset` on a NodeJS/Typescript web project with `ts-jest` and `babel-jest`, I am still getting the `SyntaxError: Unexpected token 'export'` error. Below is a copy of my `jest.config.ts` file where I attempt to merge `@cloudscape-design/jest-preset` with my settings for `ts-jest` and `babel-jest`.

* ts-jest version: 29.1.0
* babel-jest version: 29.7.0

**jest.config.ts**
```
import type {JestConfigWithTsJest} from 'ts-jest'
import {defaults as tsjPreset} from 'ts-jest/presets'
import merge from 'merge'

const config: JestConfigWithTsJest = merge.recursive(tsjPreset, {
    // Map @SRC to the src/ folder
    modulePaths: ['<rootDir>/src'],
    moduleNameMapper: {
      '^@SRC/(.*)$': '<rootDir>/src/$1',
    },

    // Enable ts-jest and have it reference test/tsconfig.json
    transform: {
      ...tsjPreset.transform,
      '^.+\\.tsx?$': [
        'ts-jest',
        {
          tsconfig: '<rootDir>/test/tsconfig.json',
        },
      ],
      '^.+\\.jsx?$': 'babel-jest',
    },
    transformIgnorePatterns: [
      '<rootDir>/node_modules/@cloudscape-design/*'
    ],
  }
)

export default config
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/jest-preset/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/jest-preset/issues) for duplicate problems

**Comment by connorlanigan** [comment]
Hi,
in the code you shared, you are not importing the Cloudscape preset. You'll need to add the Cloudscape preset in order to support the syntax used in Cloudscape's code. You can find more details in [the "Advanced usage" section](https://github.com/cloudscape-design/jest-preset?tab=readme-ov-file#advanced-usage) of the package readme.
